[package]
name = "server"
version = "0.1.0"
edition.workspace = true

[dependencies]

# Workspace member crates

routes.workspace = true

# Extrenal crates

axum.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sea-orm = "1.1.7"
